# Configuration for training the Corrective RAG model

# Model configuration
model:
  # Pre-trained model name
  model_name: "t5-large"  
  # Max sequence length 
  max_length: 512 

# Data configuration
data:
  # Path to training data file
  train_file: "path/to/train_data.txt"

# Training configuration
training:
  # Directory to save checkpoints
  save_path: "path/to/save_dir"
  # Batch size
  batch_size: 12                 
  # Number of training epochs
  num_epochs: 8                  
  # Random seed
  seed: 42                       
  # Learning rate
  learning_rate: 1e-4            
  # Gradient clipping norm
  gradient_clip: 1.0             

  # Learning rate scheduler configuration
  scheduler:
    # Scheduler type (e.g., linear, cosine)
    name: "linear"               
    # Number of warmup steps
    warmup_steps: 0              